import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs';
import{flockDefaults,flockSeeds,flockIndex,flockUrges,flockReflect,flockStep,flockStroke,flockPhotoGuide,flockThreads}from'../src/flock-threads.js';import{makeLayer,filters}from'../src/filters.js';import{looks}from'../src/looks.js';import{applyFilter}from'../src/engine.js';import{encodeRecipe,decodeRecipe,ENGINE_VERSION}from'../src/recipes.js';
const near=(a,b,e=1e-10)=>assert.ok(Math.abs(a-b)<=e,`${a} != ${b}`),image=(w,h)=>Uint8ClampedArray.from({length:w*h*4},(_,i)=>i%4===3?255:(i*37+Math.floor(i/(w*4))*13)%256),base={...flockDefaults,seed:17};
const state=(rows)=>Object.fromEntries(['x','y','vx','vy'].map((k,c)=>[k,Float64Array.from(rows,r=>r[c])]));
// Independent all-pairs oracle: no spatial buckets and no production urge/step calls.
function oracle(s,W,H,p){const out=state(Array.from(s.x,()=>[0,0,0,0])),steer=(x,y,i,normalize)=>{if(normalize&&Math.hypot(x,y)>1e-12){const l=Math.hypot(x,y);x*=2.5/l;y*=2.5/l;}x-=s.vx[i];y-=s.vy[i];const f=Math.min(1,.18/(Math.hypot(x,y)||1));return[x*f,y*f];},reflect=(q,v,E)=>{if(E===0)return[0,0];while(q<0||q>E){if(q<0){q=-q;v=-v;}if(q>E){q=2*E-q;v=-v;}}return[q,v];};
 for(let i=0;i<s.x.length;i++){let x=0,y=0,vx=0,vy=0,sx=0,sy=0,n=0,m=0;for(let j=0;j<s.x.length;j++){if(i===j)continue;const dx=s.x[j]-s.x[i],dy=s.y[j]-s.y[i],d=Math.hypot(dx,dy);if(d>p.radius)continue;x+=dx;y+=dy;vx+=s.vx[j];vy+=s.vy[j];n++;if(d<p.radius*.45){sx-=dx/(d*d);sy-=dy/(d*d);m++;}}const a=n?steer(vx/n,vy/n,i,false):[0,0],c=n?steer(x/n,y/n,i,true):[0,0],z=m?steer(sx/m,sy/m,i,true):[0,0];let ax=(a[0]*p.align+c[0]*p.cohesion+z[0]*p.separation)/100,ay=(a[1]*p.align+c[1]*p.cohesion+z[1]*p.separation)/100,f=Math.min(1,.35/(Math.hypot(ax,ay)||1));vx=s.vx[i]+ax*f;vy=s.vy[i]+ay*f;const speed=Math.hypot(vx,vy);if(speed>3){vx*=3/speed;vy*=3/speed;}else if(speed>1e-12&&speed<1){vx/=speed;vy/=speed;}else if(speed<=1e-12){vx=2.5;vy=0;}[out.x[i],out.vx[i]]=reflect(s.x[i]+vx,vx,W);[out.y[i],out.vy[i]]=reflect(s.y[i]+vy,vy,H);}return out;}
test('spatial neighbours and synchronous steering match independent all-pairs motion across bucket edges',()=>{
 let n=0;for(const r of[10,24,32,80]){const p={...base,radius:r,follow:0},s=state(Array.from({length:53},(_,i)=>[(i*37.23+.25)%100,(i*19.37+.1)%87,Math.cos(i*2.1)*2.5,Math.sin(i*2.1)*2.5])),saved=structuredClone(s);const index=flockIndex(s,100,87,r);for(let k=0;k<6;k++){const expected=oracle(s,100,87,p),actual=flockStep(s,100,87,p);for(const key of Object.keys(s))for(let i=0;i<s.x.length;i++)near(actual[key][i],expected[key][i]);Object.assign(s,actual);n++;}assert.ok(index.head.length>0);assert.notDeepEqual(s,saved);}assert.equal(n,24);
});
test('isolated, aligned, approaching and crowded agents have separate bounded behaviours',()=>{
 let s=state([[50,50,2.5,0],[60,50,2.5,0]]),u=flockUrges(s,0,[0,1],32);assert.deepEqual(u.alignment,[0,0]);assert.deepEqual(u.cohesion,[0,0]);assert.ok(u.separation[0]<0);s=state([[50,50,0,2.5],[70,50,2.5,0]]);u=flockUrges(s,0,[0,1],32);assert.ok(u.alignment[0]>0&&u.alignment[1]<0);assert.ok(u.cohesion[0]>0&&u.cohesion[1]<0);assert.deepEqual(u.separation,[0,0]);for(const k of['alignment','cohesion'])near(Math.hypot(...u[k]),.18);assert.deepEqual(flockUrges(s,0,[0],32),{alignment:[0,0],cohesion:[0,0],separation:[0,0],count:0});
});
test('coincident zero-velocity pairs receive opposite deterministic separation',()=>{const s=state([[4,4,0,0],[4,4,0,0]]),a=flockUrges(s,0,[0,1],32,17),b=flockUrges(s,1,[0,1],32,17);near(a.separation[0],-b.separation[0]);near(a.separation[1],-b.separation[1]);near(Math.hypot(...a.separation),.18);assert.deepEqual(flockUrges(s,0,[0,1],32,17),a);assert.notDeepEqual(flockUrges(s,0,[0,1],32,18),a);});
test('reflection handles repeated overshoot and freezes a collapsed axis',()=>{assert.deepEqual(flockReflect(12,3,10),[8,-3]);assert.deepEqual(flockReflect(-2,-3,10),[2,3]);assert.deepEqual(flockReflect(32,3,10),[8,-3]);assert.deepEqual(flockReflect(-32,-3,10),[8,-3]);assert.deepEqual(flockReflect(3,2,0),[0,0]);const s=state([[0,2,2.5,1]]),out=flockStep(s,0,3,{...base,follow:0});assert.equal(out.x[0],0);assert.equal(out.vx[0],0);assert.ok(out.y[0]>=0&&out.y[0]<=3);});
test('step reads an immutable snapshot, reuses a distinct buffer and limits speed and forces',()=>{const s=state([[1,1,0,0],[5,5,10,10],[9,9,.01,.01]]),saved=structuredClone(s),out=state([[0,0,0,0],[0,0,0,0],[0,0,0,0]]);assert.equal(flockStep(s,100,100,base,()=>[100,-100],out),out);assert.deepEqual(s,saved);for(let i=0;i<3;i++)assert.ok(Math.hypot(out.vx[i],out.vy[i])>=1-1e-12&&Math.hypot(out.vx[i],out.vy[i])<=3+1e-12);});
test('native capsule strokes have subpixel coverage, immutable alpha and no intermediate byte rounding',()=>{const w=7,h=5,out=new Float32Array(w*h*4);for(let i=3;i<out.length;i+=4)out[i]=123;flockStroke(out,w,h,1,2,5,2,1,[100,50,25],.2);near(out[(2*w+3)*4],20,1e-6);near(out[(2*w)*4],0);near(out[(w+3)*4],0);assert.equal(out[(2*w+3)*4+3],123);const fractional=new Float32Array(4);for(let k=0;k<5;k++)flockStroke(fractional,1,1,0,0,0,0,.3,[1,0,0],.1);assert.ok(fractional[0]>.1&&fractional[0]<1);});
test('photo guide uses native source gradients and selects the tangent agreeing with current velocity',()=>{const w=1537,h=5,a=new Uint8ClampedArray(w*h*4);for(let y=0;y<h;y++)for(let x=0;x<w;x++){const i=(y*w+x)*4;a[i]=a[i+1]=a[i+2]=x<1200?0:255;a[i+3]=255;}const g=flockPhotoGuide(a,w,h,1),up=g(1200,2,0,2.5),down=g(1200,2,0,-2.5),side=g(1200,2,2.5,0);for(const v of [...up,...down])near(v,0);assert.ok(side[0]<0&&side[1]>0);assert.deepEqual(g(1100,2,2.5,0),[0,0]);const b=a.slice();b.fill(0);assert.deepEqual(flockPhotoGuide(b,w,h,1)(1200,2,2.5,0),[0,0]);});
test('seeds retain normalized motion, aspect density and bilinear native colour across resized photos',()=>{const a=image(200,100),b=image(400,200),s=flockSeeds(a,200,100,base),t=flockSeeds(b,400,200,base);assert.equal(s.s.x.length,1125);assert.equal(t.s.x.length,1125);near(s.scale,.2);near(t.scale,.4);for(let i=0;i<10;i++){near(s.s.x[i]/s.W,t.s.x[i]/t.W);near(s.s.y[i]/s.H,t.s.y[i]/t.H);near(Math.hypot(s.s.vx[i],s.s.vy[i]),2.5);}const uniform=Uint8ClampedArray.from({length:20*10*4},(_,i)=>[40,100,200,255][i%4]);assert.deepEqual(Array.from(flockSeeds(uniform,20,10,base).rgb.slice(0,3)),[40,100,200]);});
test('zero time/amount return owned exact originals; partial amount blends the same floating simulation',()=>{const w=97,h=71,a=image(w,h),saved=a.slice(),p={...base,time:18,density:10};for(const q of[{...p,time:0},{...p,amount:0}]){const out=flockThreads(a,w,h,q);assert.notEqual(out,a);assert.deepEqual(out,a);}const full=flockThreads(a,w,h,p),partial=flockThreads(a,w,h,{...p,amount:35});for(let i=0;i<a.length;i++)if(i%4!==3)near(partial[i],a[i]+.35*(full[i]-a[i]),1);assert.deepEqual(a,saved);});
test('all twelve controls and the seed change the render and restore exactly',()=>{const w=239,h=167,a=image(w,h),initial=flockThreads(a,w,h,base),changes={time:120,density:75,radius:60,align:0,cohesion:100,separation:0,follow:0,width:3,carry:0,photo:70,paper:100,amount:50,seed:55};for(const[key,value]of Object.entries(changes))assert.notDeepEqual(flockThreads(a,w,h,{...base,[key]:value}),initial,key);assert.deepEqual(flockThreads(a,w,h,base),initial);});
test('native long edges, tiny axes and extreme settings preserve dimensions, finite channels and input ownership',()=>{for(const[w,h]of[[1,1],[1,47],[47,1],[3,7],[1537,3]]){const a=image(w,h),saved=a.slice(),out=flockThreads(a,w,h,{...base,time:9,density:100,radius:80,width:5,carry:0,paper:100});assert.equal(out.length,a.length);assert.notEqual(out,a);for(let i=3;i<out.length;i+=4)assert.equal(out[i],255);assert.deepEqual(a,saved);}});
test('seeded trajectories avoid ambient randomness and state from another photo',()=>{const a=image(173,129),b=image(129,173),p={...base,time:15,density:10},original=Math.random;Math.random=()=>{throw Error('ambient randomness');};try{const out=flockThreads(a,173,129,p);flockThreads(b,129,173,{...p,seed:84});assert.deepEqual(flockThreads(a,173,129,p),out);}finally{Math.random=original;}});
test('engine equals the native core on opaque inputs, supports alpha, mix, monochrome and inversion',()=>{const w=151,h=113,a=image(w,h),l=makeLayer('flockthreads'),p={...l.params,time:15,density:10};assert.deepEqual(applyFilter(a,w,h,{...l,params:p}),flockThreads(a,w,h,p));for(let i=3;i<a.length;i+=4)a[i]=i*7%256;const saved=a.slice(),full=applyFilter(a,w,h,{...l,params:p}),zero=applyFilter(a,w,h,{...l,params:{...p,mix:0}}),mono=applyFilter(a,w,h,{...l,params:{...p,colorMode:'mono'}}),invert=applyFilter(a,w,h,{...l,params:{...p,invert:true}});for(let i=0;i<a.length;i+=4){for(let c=0;c<3;c++){near(zero[i+c],a[i+c]*a[i+3]/255+255-a[i+3],.5);assert.equal(invert[i+c],255-full[i+c]);}assert.equal(full[i+3],255);assert.equal(mono[i],mono[i+1]);assert.equal(mono[i+1],mono[i+2]);}assert.deepEqual(a,saved);});
test('0.43 adds flock threads, accepts 0.42 islands and round-trips all public presets',()=>{assert.equal(ENGINE_VERSION,'0.77');assert.equal(filters.length,129);assert.equal(looks.length,261);assert.equal(filters.find(f=>f.flockthreads).controls.length,12);const l=makeLayer('flockthreads');assert.deepEqual(decodeRecipe(encodeRecipe([l])),[l]);for(let n=2;n<=42;n++)assert.throws(()=>decodeRecipe(JSON.stringify({...JSON.parse(encodeRecipe([l])),engine:'0.'+n})));const old=makeLayer('componentislands');assert.deepEqual(decodeRecipe(JSON.stringify({...JSON.parse(encodeRecipe([old])),engine:'0.42'})),[old]);for(const[key,value]of[['time',1.5],['density',9],['radius',81],['width',.29],['carry',101],['amount',-1],['seed',.5]])assert.throws(()=>decodeRecipe(encodeRecipe([{...l,params:{...l.params,[key]:value}}])));assert.doesNotThrow(()=>decodeRecipe(encodeRecipe([{...l,params:{...l.params,width:.65}}])));let count=0;for(const file of fs.readdirSync(new URL('../public/recipes/',import.meta.url)).filter(f=>f.endsWith('.json'))){const look=looks.find(l=>l.id===file.slice(0,-5));assert.ok(look);assert.deepEqual(decodeRecipe(fs.readFileSync(new URL('../public/recipes/'+file,import.meta.url),'utf8')),look.layers);count++;}assert.equal(count,234);});
