import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs';
import{miuraDefaults,miuraDimensions,miuraPoint,miuraClip,miuraSheet,miuraMesh,miuraPhoto}from'../src/miura-photo.js';import{rasterRender}from'../src/raster-relief.js';
import{makeLayer,filters}from'../src/filters.js';import{looks}from'../src/looks.js';import{applyFilter,renderPipeline}from'../src/engine.js';import{encodeRecipe,decodeRecipe,ENGINE_VERSION}from'../src/recipes.js';
const q=(p={})=>({...miuraDefaults,...p}),image=(w,h)=>Uint8ClampedArray.from({length:w*h*4},(_,i)=>i%4===3?255:(i*37+Math.floor(i/(w*4))*13)%256),close=(a,b,e=1e-8)=>assert.ok(Math.abs(a-b)<e,`${a} / ${b}`),byte=v=>new Uint8ClampedArray([v])[0],sub=(a,b)=>a.slice(0,3).map((v,i)=>v-b[i]),dot=(a,b)=>a.reduce((s,v,i)=>s+v*b[i],0),cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],areaUV=p=>Math.abs(p.reduce((s,a,i)=>{const b=p[(i+1)%p.length];return s+a[3]*b[4]-b[3]*a[4];},0))/2,area3D=p=>p.slice(1,-1).reduce((s,a,i)=>s+Math.hypot(...cross(sub(a,p[0]),sub(p[i+2],p[0])))/2,0);
const flat=q({fold:0,tilt:0,turn:0,size:100,shade:0,lift:0});
test('Miura unit dimensions match known angles, flat limit and one-dimensional accordion',()=>{
 const d=miuraDimensions(2,3,60,60);close(d.H,1.5);close(d.L,Math.sqrt(7)/2);close(d.S,3*Math.sqrt(3/7));close(d.V,6/Math.sqrt(7));const f=miuraDimensions(2,3,60,0);close(f.H,0);close(f.L,2);close(f.S,3*Math.sqrt(3)/2);close(f.V,1.5);const a=miuraDimensions(2,3,90,60);close(a.L,1);close(a.H,Math.sqrt(3));close(a.S,3);close(a.V,0);
});
test('alternating parallelograms preserve lengths, acute angle, area and planarity as they fold',()=>{
 for(const theta of[0,28,68,82])for(const gamma of[20,62,80]){const d=miuraDimensions(13,21,gamma,theta);for(const i of[-1,0,1])for(const j of[0,1]){const A=miuraPoint(i,j,d),B=miuraPoint(i+1,j,d),C=miuraPoint(i+1,j+1,d),D=miuraPoint(i,j+1,d),u=sub(B,A),v=sub(D,A),n=cross(u,v);close(Math.hypot(...u),13);close(Math.hypot(...v),21);close(Math.abs(dot(u,v))/13/21,Math.cos(gamma*Math.PI/180));close(Math.hypot(...n),13*21*Math.sin(gamma*Math.PI/180));close(dot(n,sub(C,A)),0);close(Math.abs(n[2])/Math.hypot(...n),Math.cos(theta*Math.PI/180));}}
});
test('UV rectangle clipping interpolates the same affine 3D surface and does not mutate the input',()=>{
 const make=(u,v)=>[2*(u+2),3*(v+1),u-v,u,v],poly=[make(-2,-1),make(2,-1),make(2,3),make(-2,3)],saved=poly.map(a=>a.slice());let clipped=poly;for(const[axis,value,greater]of[[3,0,true],[3,1,false],[4,0,true],[4,2,false]])clipped=miuraClip(clipped,axis,value,greater);assert.equal(clipped.length,4);close(areaUV(clipped),2);for(const a of clipped){assert.ok(a[3]>=0&&a[3]<=1&&a[4]>=0&&a[4]<=2);assert.deepEqual(a,make(a[3],a[4]));}assert.deepEqual(poly,saved);assert.deepEqual(miuraClip(poly,3,5,true),[]);
});
test('clipped sheet covers the complete photograph once, retains physical area and shared crease positions',()=>{
 const w=87,h=65;for(const direction of[0,1])for(const fold of[0,42,82]){const sheet=miuraSheet(w,h,q({direction,fold,cells:7,ratio:73,angle:57})),seen=new Map();let uv=0,area=0;for(const f of sheet.faces){uv+=areaUV(f.points);area+=area3D(f.points);for(const p of f.points){assert.ok(p[3]>=-1e-10&&p[3]<=w+1e-10&&p[4]>=-1e-10&&p[4]<=h+1e-10);const key=p[3].toFixed(7)+','+p[4].toFixed(7),old=seen.get(key);if(old)for(let c=0;c<3;c++)close(old[c],p[c],1e-6);else seen.set(key,p);}close(Math.abs(f.normal[2]),Math.cos(fold*Math.PI/180));}close(uv,w*h,1e-7);close(area,w*h,1e-7);}
});
test('unfolded native texture matches an independent four-ray bilinear oracle without holes',()=>{
 const w=7,h=5,a=image(w,h),out=miuraPhoto(a,w,h,flat),at=(x,y,c)=>{x=Math.max(0,Math.min(w-1,x));y=Math.max(0,Math.min(h-1,y));const X=Math.floor(x),Y=Math.floor(y),fx=x-X,fy=y-Y;let s=0;for(let yy=0;yy<2;yy++)for(let xx=0;xx<2;xx++)s+=a[(Math.min(h-1,Y+yy)*w+Math.min(w-1,X+xx))*4+c]*(xx?fx:1-fx)*(yy?fy:1-fy);return s;};for(let y=0;y<h;y++)for(let x=0;x<w;x++)for(let c=0;c<3;c++){let sum=0;for(const yy of[-.25,.25])for(const xx of[-.25,.25])sum+=at(x+xx,y+yy,c);assert.equal(out[(y*w+x)*4+c],byte(sum/4));}assert.deepEqual(a,image(w,h));assert.deepEqual(miuraPhoto(a,w,h,{...flat,direction:1}),out);
});
test('fixed magnification preserves contraction instead of fitting each folded shape back to full size',()=>{
 const w=87,h=65,extent=m=>Math.max(...Array.from({length:m.vertices.length/6},(_,j)=>m.vertices[j*6]))-Math.min(...Array.from({length:m.vertices.length/6},(_,j)=>m.vertices[j*6]));const open=miuraMesh(miuraSheet(w,h,flat),w,h,flat),p={...flat,fold:68},sheet=miuraSheet(w,h,p),closed=miuraMesh(sheet,w,h,p),half=miuraMesh(sheet,w,h,{...p,size:50});close(extent(open),w);assert.ok(extent(closed)<w*.9);close(extent(half),extent(closed)*.5);close(extent(closed),closed.bounds[3]-closed.bounds[0]);
});
test('deep folded occlusion preserves texture when triangle order and winding are reversed',()=>{
 const w=119,h=83,a=image(w,h),p=q({fold:76,tilt:-69,turn:37,size:140,shade:0}),m=miuraMesh(miuraSheet(w,h,p),w,h,p),A=rasterRender(a,w,h,m,p),B=rasterRender(a,w,h,{...m,indices:m.indices.slice().reverse()},p);assert.deepEqual(A,B);assert.ok(A.some((v,i)=>i%4!==3&&v!==byte(p.paper*2.55)));
});
test('tile boundaries do not change folded coverage, depth or native photo sampling',()=>{
 const w=119,h=83,a=image(w,h),p=q({fold:73,tilt:57,turn:-33,size:140}),m=miuraMesh(miuraSheet(w,h,p),w,h,p);assert.deepEqual(rasterRender(a,w,h,m,p,{tile:96}),rasterRender(a,w,h,m,p,{tile:13}));
});
test('all twelve controls change output and restoring settings is deterministic without a layout seed',()=>{
 const w=320,h=256,a=image(w,h),base=miuraPhoto(a,w,h),values={cells:17,ratio:155,angle:35,fold:73,tilt:-43,turn:47,direction:1,size:70,light:75,shade:0,paper:12,lift:65};for(const[k,v]of Object.entries(values))assert.notDeepEqual(miuraPhoto(a,w,h,{[k]:v}),base,k);assert.deepEqual(miuraPhoto(a,w,h),base);assert.deepEqual(miuraPhoto(a,w,h,{seed:9917}),base);assert.equal(filters.find(f=>f.miuraphoto).random,false);
});
test('a one-pixel change beyond 1536 survives through the native photo UV without a reduced field',()=>{
 const w=1537,h=7,a=new Uint8ClampedArray(w*h*4).fill(90),b=a.slice();b[(3*w+1535)*4]=240;const m=miuraMesh(miuraSheet(w,h,flat),w,h,flat);close(Math.max(...Array.from({length:m.vertices.length/6},(_,i)=>m.vertices[i*6+3]))+.5,w);assert.notDeepEqual(miuraPhoto(a,w,h,flat),miuraPhoto(b,w,h,flat));assert.deepEqual(a,new Uint8ClampedArray(w*h*4).fill(90));
});
test('tiny axes and all bounded extremes return finite opaque owned pixels including Buffers',()=>{
 for(const[w,h]of[[1,1],[1,19],[23,1],[31,29]])for(const end of[2,3]){const a=image(w,h),saved=a.slice(),p=Object.fromEntries(filters.find(f=>f.miuraphoto).controls.map(c=>[c[0],c[end]])),A=miuraPhoto(a,w,h,p),B=miuraPhoto(Buffer.from(a),w,h,p);assert.deepEqual(A,B);assert.notEqual(A,a);assert.equal(A.length,a.length);assert.ok(A.every(Number.isFinite));for(let i=3;i<A.length;i+=4)assert.equal(A[i],255);assert.deepEqual(a,saved);assert.ok(miuraMesh(miuraSheet(w,h,q(p)),w,h,q(p)).vertices.every(Number.isFinite));}
});
test('common colour, alpha flattening, inverse and mix apply once without extra-photo state',()=>{
 const w=73,h=61,a=image(w,h),l=makeLayer('miuraphoto'),p={...l.params,brightness:17,contrast:120,saturation:40},prep=applyFilter(a,w,h,{id:'mono',params:{...p,mix:100,invert:false}}),out=applyFilter(a,w,h,{...l,params:p});assert.deepEqual(out,miuraPhoto(prep,w,h,p));const mixed=applyFilter(a,w,h,{...l,params:{...p,invert:true,mix:25}});for(let i=0;i<a.length;i++)if(i%4!==3)assert.equal(mixed[i],byte(a[i]+(255-out[i]-a[i])*.25));assert.deepEqual(applyFilter(a,w,h,{...l,params:{...p,mix:0}}),a);const mono=applyFilter(a,w,h,{...l,params:{...p,colorMode:'mono'}});for(let i=0;i<mono.length;i+=4)assert.equal(mono[i],mono[i+1]),assert.equal(mono[i+1],mono[i+2]);assert.deepEqual(applyFilter(new Uint8ClampedArray(a.length),w,h,l),applyFilter(new Uint8ClampedArray(a.length).fill(255),w,h,l));const old=makeLayer('mono'),r={near:{pixels:image(19,23),width:19,height:23}};assert.deepEqual(renderPipeline(a,w,h,[old,l],r),applyFilter(applyFilter(a,w,h,old),w,h,l));
});
test('0.63 gates folding, accepts 0.62 photo film and round-trips all 196 public recipes',()=>{
 assert.equal(ENGINE_VERSION,'0.77');assert.equal(filters.length,129);assert.equal(looks.length,261);const f=filters.find(f=>f.miuraphoto),l=makeLayer(f.id);assert.equal(f.controls.length,12);assert.equal(looks.filter(l=>l.miuraphoto).length,3);assert.deepEqual(decodeRecipe(encodeRecipe([l])),[l]);for(let n=2;n<=62;n++)assert.throws(()=>decodeRecipe(JSON.stringify({...JSON.parse(encodeRecipe([l])),engine:'0.'+n})));for(const[id,engine]of[['transmittedfilm','0.62'],['rasterrelief','0.61'],['hybridimage','0.60']]){const old=makeLayer(id);assert.deepEqual(decodeRecipe(JSON.stringify({...JSON.parse(encodeRecipe([old])),engine})),[old]);}for(const[k,,lo,hi,step]of f.controls)for(const v of[lo-step,hi+step,lo+step*.5])assert.throws(()=>decodeRecipe(encodeRecipe([{...l,params:{...l.params,[k]:v}}])),k);let count=0;for(const file of fs.readdirSync(new URL('../public/recipes/',import.meta.url)).filter(f=>f.endsWith('.json'))){const look=looks.find(l=>l.id===file.slice(0,-5));assert.ok(look);assert.deepEqual(decodeRecipe(fs.readFileSync(new URL('../public/recipes/'+file,import.meta.url),'utf8')),look.layers);count++;}assert.equal(count,234);
});
