import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs';
import{mirrorDefaults,mirrorNormal,mirrorDirection,mirrorUV,mirrorSample,mirrorLayout,photoMirrors}from'../src/photo-mirrors.js';
import{makeLayer,filters}from'../src/filters.js';import{looks}from'../src/looks.js';import{applyFilter,renderPipeline}from'../src/engine.js';import{encodeRecipe,decodeRecipe,ENGINE_VERSION}from'../src/recipes.js';
const q=(p={})=>({...mirrorDefaults,...p}),close=(a,b,e=1e-8)=>assert.ok(Math.abs(a-b)<e,`${a} / ${b}`),byte=v=>new Uint8ClampedArray([v])[0],image=(w,h)=>Uint8ClampedArray.from({length:w*h*4},(_,i)=>i%4===3?255:(i*37+Math.floor(i/(w*4))*13)%256);
const sphere=q({shape:0,aspect:100,bulge:100,turn:0});
function independentSample(a,w,h,x,y,c){const xx=Math.max(0,Math.min(w-1,x)),yy=Math.max(0,Math.min(h-1,y)),i=Math.floor(xx),j=Math.floor(yy),fx=xx-i,fy=yy-j;let v=0;for(let dx=0;dx<2;dx++)for(let dy=0;dy<2;dy++)v+=a[(Math.min(h-1,j+dy)*w+Math.min(w-1,i+dx))*4+c]*(dx?fx:1-fx)*(dy?fy:1-fy);return v;}
function oracle(a,w,h,p,objects){const out=new Uint8ClampedArray(a.length);for(let y=0;y<h;y++)for(let x=0;x<w;x++){const sum=[0,0,0];for(const dy of[.25,.75])for(const dx of[.25,.75]){let best=null;for(const o of objects){const nx=(x+dx-o.cx)/o.r,ny=(y+dy-o.cy)/o.r,rr=nx*nx+ny*ny;if(rr>1)continue;const nz=Math.sqrt(1-rr),z=nz*o.r;if(!best||z>best.z||(z===best.z&&o.id<best.id))best={nx,ny,nz,z,id:o.id};}let uv;if(best){const rx=2*best.nz*best.nx,ry=2*best.nz*best.ny,rz=2*best.nz*best.nz-1,longitude=.25+Math.atan2(rx,rz)/(2*Math.PI),u=1-Math.abs(2*(longitude-Math.floor(longitude))-1),v=.5+Math.asin(Math.max(-1,Math.min(1,ry)))/Math.PI;uv=[u*w-.5,v*h-.5];}for(let c=0;c<3;c++)sum[c]+=uv?independentSample(a,w,h,uv[0],uv[1],c):p.paper*2.55+(independentSample(a,w,h,x+dx-.5,y+dy-.5,c)-p.paper*2.55)*p.background/100;}for(let c=0;c<3;c++)out[(y*w+x)*4+c]=byte(sum[c]/4);out[(y*w+x)*4+3]=255;}return out;}
test('sphere and ring have known analytic depths, normals and open silhouettes',()=>{
 const c=mirrorNormal(0,0,sphere);assert.deepEqual(c,{n:[0,0,1],z:1});const n=mirrorNormal(.3,.4,sphere);close(n.z,Math.sqrt(.75));for(let j=0;j<3;j++)close(n.n[j],[.3,.4,Math.sqrt(.75)][j]);assert.equal(mirrorNormal(1.01,0,sphere),null);const p=q({shape:1,aspect:100,bulge:100,turn:0,hole:40});assert.equal(mirrorNormal(.399,0,p),null);assert.equal(mirrorNormal(1.001,0,p),null);const top=mirrorNormal(.7,0,p);close(top.z,.3);close(top.n[0],0);close(top.n[2],1);assert.ok(mirrorNormal(.5,0,p).n[0]<0);assert.ok(mirrorNormal(.9,0,p).n[0]>0);
});
test('rotated and stretched normals agree with independent implicit-surface gradients',()=>{
 for(const shape of[0,1])for(const aspect of[50,115,200])for(const bulge of[20,100,180]){const p=q({shape,aspect,bulge,turn:37}),X=.72,Y=.15,n=mirrorNormal(X,Y,p),s=Math.sqrt(aspect/100),a=p.turn*Math.PI/180,x=X/s*Math.cos(a)-Y*s*Math.sin(a),y=X/s*Math.sin(a)+Y*s*Math.cos(a),z=n.z,F=(x,y,z)=>{const u=(x*Math.cos(a)+y*Math.sin(a))*s,v=(-x*Math.sin(a)+y*Math.cos(a))/s,t=z/(bulge/100);if(!shape)return u*u+v*v+t*t-1;const R=(1+p.hole/100)/2,r=(1-p.hole/100)/2;return(u*u+v*v+t*t+R*R-r*r)**2-4*R*R*(u*u+v*v);},e=1e-6,g=[(F(x+e,y,z)-F(x-e,y,z))/(2*e),(F(x,y+e,z)-F(x,y-e,z))/(2*e),(F(x,y,z+e)-F(x,y,z-e))/(2*e)],len=Math.hypot(...g);close(F(x,y,z),0);for(let j=0;j<3;j++)close(n.n[j],g[j]/len,1e-7);close(Math.hypot(...n.n),1);}
});
test('specular direction preserves unit length and equal normal angles with known limits',()=>{
 assert.deepEqual(mirrorDirection([0,0,1]),[0,0,1]);assert.deepEqual(mirrorDirection([1,0,0]),[0,0,-1]);const r=mirrorDirection([Math.SQRT1_2,0,Math.SQRT1_2]);close(r[0],1);close(r[2],0);for(const x of[.1,.5,.8])for(const y of[-.3,0,.3]){const n=mirrorNormal(x,y,sphere).n,R=mirrorDirection(n);close(Math.hypot(...R),1);close(R.reduce((s,v,i)=>s+v*n[i],0),n[2]);}
});
test('angular environment mapping rotates known directions and stays continuous across the back seam at every zoom',()=>{
 const p=q({yaw:0,pitch:0,zoom:100});assert.deepEqual(mirrorUV([0,0,1],p),[.5,.5]);assert.deepEqual(mirrorUV([1,0,0],p),[1,.5]);assert.deepEqual(mirrorUV([-1,0,0],p),[0,.5]);assert.deepEqual(mirrorUV([0,1,0],p),[.5,1]);assert.deepEqual(mirrorUV([0,-1,0],p),[.5,0]);close(mirrorUV([0,0,1],{...p,yaw:90})[0],1);close(mirrorUV([0,0,1],{...p,pitch:90})[1],0);for(const zoom of[40,73,100,155,220]){const a=mirrorUV([1e-10,0,-1],{...p,zoom}),b=mirrorUV([-1e-10,0,-1],{...p,zoom});for(let c=0;c<2;c++)close(a[c],b[c],1e-8);assert.ok(a.every(v=>v>=0&&v<=1));}const u=mirrorUV([Math.SQRT1_2,0,Math.SQRT1_2],{...p,zoom:200});close(u[0],.625);
});
test('native bilinear colour uses half-pixel UV centres and clamped edges rather than wrapping unrelated photo edges',()=>{
 const w=3,h=2,a=image(w,h);for(const u of[0,1/6,.5,.91,1])for(const v of[0,.25,.61,1])for(let c=0;c<3;c++)close(mirrorSample(a,w,h,u,v,c),independentSample(a,w,h,u*w-.5,v*h-.5,c));for(let c=0;c<3;c++){assert.equal(mirrorSample(a,w,h,0,0,c),a[c]);assert.equal(mirrorSample(a,w,h,1,1,c),a[(w*h-1)*4+c]);}
});
test('the complete four-point sphere render matches an independent reflection and bilinear oracle including background',()=>{
 const w=9,h=11,a=image(w,h),p={...sphere,size:90,background:37,paper:23},r=Math.min(w,h)*p.size/200,objects=[{cx:w/2,cy:h/2,r,id:0}];assert.deepEqual(photoMirrors(a,w,h,p),oracle(a,w,h,p,objects));assert.deepEqual(a,image(w,h));
});
test('overlapping mirrors select physical front depths independently of object iteration and preserve background through a ring hole',()=>{
 const w=13,h=9,a=image(w,h),p={...sphere,paper:12,background:0},objects=[{cx:5,cy:4.5,r:3.5,id:0},{cx:7,cy:4.5,r:4.5,id:1}].map(o=>({...o,ex:o.r,ey:o.r,ca:1,sa:0,aspect:1})),out=photoMirrors(a,w,h,p,{objects});assert.deepEqual(out,oracle(a,w,h,p,objects));assert.deepEqual(out,photoMirrors(a,w,h,p,{objects:objects.slice().reverse()}));const ring=q({shape:1,aspect:100,turn:0,copies:1,size:90});const hole=photoMirrors(a,w,h,ring);for(let c=0;c<3;c++)assert.equal(hole[(4*w+6)*4+c],byte(ring.paper*2.55));
});
test('small tiles retain all rotated elliptical bounds, overlaps and four-point silhouette coverage',()=>{
 const w=117,h=83,a=image(w,h);for(const shape of[0,1]){const p=q({shape,copies:13,size:180,aspect:200,bulge:73,turn:37,yaw:-71,pitch:33,zoom:155,background:27});assert.deepEqual(photoMirrors(a,w,h,p,{tile:13}),photoMirrors(a,w,h,p,{tile:96}));}for(const copies of[1,3,13,24])assert.equal(mirrorLayout(w,h,q({copies})).length,copies);
});
test('all twelve active ring controls alter output, restore deterministically and do not depend on a seed',()=>{
 const w=160,h=133,a=image(w,h),base=photoMirrors(a,w,h),values={shape:0,copies:7,size:70,aspect:165,bulge:43,hole:70,turn:47,yaw:75,pitch:-43,zoom:155,paper:12,background:65};for(const[k,v]of Object.entries(values))assert.notDeepEqual(photoMirrors(a,w,h,{[k]:v}),base,k);assert.deepEqual(photoMirrors(a,w,h),base);assert.deepEqual(photoMirrors(a,w,h,{seed:971}),base);assert.deepEqual(photoMirrors(a,w,h,{shape:0,hole:10}),photoMirrors(a,w,h,{shape:0,hole:80}));assert.equal(filters.find(f=>f.photomirrors).random,false);
});
test('a source pixel beyond 1536 reaches the actual reflected image without a reduced texture field',()=>{
 const w=1601,h=61,a=new Uint8ClampedArray(w*h*4).fill(80),p={...sphere,size:180},o=mirrorLayout(w,h,p)[0],x=Math.round(o.cx+o.r*.707),y=Math.floor(o.cy),n=mirrorNormal((x+.25-o.cx)/o.r,(y+.25-o.cy)/o.r,p),uv=mirrorUV(mirrorDirection(n.n),p),sx=Math.round(uv[0]*w-.5),sy=Math.round(uv[1]*h-.5);assert.ok(sx>1536&&sx<w);const b=a.slice();b[(sy*w+sx)*4]=255;assert.notDeepEqual(photoMirrors(a,w,h,p),photoMirrors(b,w,h,p));assert.deepEqual(a,new Uint8ClampedArray(a.length).fill(80));
});
test('tiny axes and all bounded extremes return finite opaque owned pixels with Buffer input protected',()=>{
 const controls=filters.find(f=>f.photomirrors).controls;for(const[w,h]of[[1,1],[1,19],[23,1],[31,29]])for(const end of[2,3]){const a=image(w,h),p=Object.fromEntries(controls.map(c=>[c[0],c[end]])),out=photoMirrors(a,w,h,p);assert.deepEqual(out,photoMirrors(Buffer.from(a),w,h,p));assert.equal(out.length,a.length);assert.notEqual(out,a);assert.ok(out.every(Number.isFinite));for(let i=3;i<out.length;i+=4)assert.equal(out[i],255);assert.deepEqual(a,image(w,h));}
});
test('common alpha flattening, colour, inverse and mix apply once without extra-photo state',()=>{
 const w=73,h=61,a=image(w,h),l=makeLayer('photomirrors'),p={...l.params,brightness:17,contrast:120,saturation:40},prep=applyFilter(a,w,h,{id:'mono',params:{...p,mix:100,invert:false}}),out=applyFilter(a,w,h,{...l,params:p});assert.deepEqual(out,photoMirrors(prep,w,h,p));const mixed=applyFilter(a,w,h,{...l,params:{...p,invert:true,mix:25}});for(let i=0;i<a.length;i++)if(i%4!==3)assert.equal(mixed[i],byte(a[i]+(255-out[i]-a[i])*.25));assert.deepEqual(applyFilter(a,w,h,{...l,params:{...p,mix:0}}),a);const mono=applyFilter(a,w,h,{...l,params:{...p,colorMode:'mono'}});for(let i=0;i<mono.length;i+=4)assert.equal(mono[i],mono[i+1]),assert.equal(mono[i+1],mono[i+2]);assert.deepEqual(applyFilter(new Uint8ClampedArray(a.length),w,h,l),applyFilter(new Uint8ClampedArray(a.length).fill(255),w,h,l));const old=makeLayer('mono');assert.deepEqual(renderPipeline(a,w,h,[old,l],{near:{pixels:image(19,23),width:19,height:23}}),applyFilter(applyFilter(a,w,h,old),w,h,l));
});
test('0.64 gates mirrors, preserves 0.63 folding and round-trips all 199 public recipes and every bounded control',()=>{
 assert.equal(ENGINE_VERSION,'0.77');assert.equal(filters.length,129);assert.equal(looks.length,261);const f=filters.find(f=>f.photomirrors),l=makeLayer(f.id);assert.equal(f.controls.length,12);assert.equal(looks.filter(l=>l.photomirrors).length,3);assert.deepEqual(decodeRecipe(encodeRecipe([l])),[l]);for(let n=2;n<=63;n++)assert.throws(()=>decodeRecipe(JSON.stringify({...JSON.parse(encodeRecipe([l])),engine:'0.'+n})));for(const[id,engine]of[['miuraphoto','0.63'],['transmittedfilm','0.62'],['rasterrelief','0.61'],['hybridimage','0.60']]){const old=makeLayer(id);assert.deepEqual(decodeRecipe(JSON.stringify({...JSON.parse(encodeRecipe([old])),engine})),[old]);}for(const[k,,lo,hi,step]of f.controls)for(const v of[lo-step,hi+step,lo+step*.5])assert.throws(()=>decodeRecipe(encodeRecipe([{...l,params:{...l.params,[k]:v}}])),k);let count=0;for(const file of fs.readdirSync(new URL('../public/recipes/',import.meta.url)).filter(f=>f.endsWith('.json'))){const look=looks.find(l=>l.id===file.slice(0,-5));assert.ok(look);assert.deepEqual(decodeRecipe(fs.readFileSync(new URL('../public/recipes/'+file,import.meta.url),'utf8')),look.layers);count++;}assert.equal(count,234);
});
