import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs';
import{sandDefaults,sandInitial,sandRound,sandEvolve,sandColour,sandAvalanches}from'../src/sand-avalanches.js';
import{makeLayer,filters}from'../src/filters.js';import{looks}from'../src/looks.js';import{applyFilter}from'../src/engine.js';import{encodeRecipe,decodeRecipe,ENGINE_VERSION}from'../src/recipes.js';
const base={...sandDefaults,seed:17},sum=a=>a.reduce((a,b)=>a+b,0),image=(w,h)=>Uint8ClampedArray.from({length:w*h*4},(_,i)=>i%4===3?255:(i*37+Math.floor(i/(w*4))*13)%256);
const near=(a,b,e=1)=>assert.ok(Math.abs(a-b)<=e,`${a} != ${b}`);
function neighbours(i,w,h,hop){const x=i%w,y=Math.floor(i/w);return [[x-hop,y],[x+hop,y],[x,y-hop],[x,y+hop]].map(([xx,yy])=>xx>=0&&xx<w&&yy>=0&&yy<h?yy*w+xx:-1);}
function scatter(a,w,h,hop,loss){const out=Array.from(a),odometer=new Uint32Array(a.length),threshold=4+loss;let lost=0;for(let i=0;i<a.length;i++){const q=Math.floor(a[i]/threshold);odometer[i]=q;out[i]-=threshold*q;lost+=loss*q;for(const j of neighbours(i,w,h,hop))if(j<0)lost+=q;else out[j]+=q;}return{height:Uint32Array.from(out),odometer,lost};}
function stabilize(a,w,h,hop,loss,reverse=false){const out=Array.from(a),odo=new Uint32Array(a.length),threshold=4+loss;let operations=0;for(;;){let changed=false;for(let k=0;k<a.length;k++){const i=reverse?a.length-1-k:k;if(out[i]<threshold)continue;out[i]-=threshold;odo[i]++;for(const j of neighbours(i,w,h,hop))if(j>=0)out[j]++;changed=true;if(++operations>2000000)throw Error('oracle did not stabilize');}if(!changed)return{height:Uint32Array.from(out),odometer:odo};}}
test('synchronous bulk toppling matches independent scatter and accounts for every boundary and extra-sink grain',()=>{
 for(const[w,h]of[[1,1],[1,17],[17,1],[13,11],[1537,3]])for(const hop of[1,2,7])for(const loss of[0,1,5]){const a=Uint32Array.from({length:w*h},(_,i)=>i*17%53),saved=a.slice(),oracle=scatter(a,w,h,hop,loss),odo=new Uint32Array(a.length),actual=sandRound(a,w,h,hop,loss,odo);assert.deepEqual(actual.height,oracle.height);assert.deepEqual(odo,oracle.odometer);assert.equal(actual.lost,oracle.lost);assert.equal(actual.fired,sum(odo));assert.equal(sum(a),sum(actual.height)+actual.lost);assert.deepEqual(a,saved);assert.notEqual(a,actual.height);}
});
test('the accumulated odometer satisfies an independent native graph Laplacian after finite rounds',()=>{
 for(const[w,h,hop,loss,steps]of[[9,7,1,0,1],[9,7,2,1,7],[1,13,3,0,19],[17,1,4,2,31],[1537,3,5,0,12]]){const a=Uint32Array.from({length:w*h},(_,i)=>i*29%97),saved=a.slice(),s=sandEvolve(a,w,h,hop,loss,steps);for(let i=0;i<a.length;i++){let predicted=a[i]-(4+loss)*s.odometer[i];for(const j of neighbours(i,w,h,hop))if(j>=0)predicted+=s.odometer[j];assert.equal(s.height[i],predicted);}assert.equal(sum(a),sum(s.height)+s.trace.reduce((a,b)=>a+b.lost,0));assert.ok(s.height.every(v=>v>=0&&Number.isInteger(v)));assert.deepEqual(a,saved);}
});
test('full stabilization agrees with two independent sequential legal firing orders on several native graphs',()=>{
 for(const[w,h,hop,loss]of[[7,5,1,0],[7,5,2,0],[7,5,3,1],[1,13,2,0],[13,1,4,3]]){const a=Uint32Array.from({length:w*h},(_,i)=>i*13%37),f=stabilize(a,w,h,hop,loss),r=stabilize(a,w,h,hop,loss,true),actual=sandEvolve(a,w,h,hop,loss,2000);assert.deepEqual(actual.height,f.height);assert.deepEqual(actual.odometer,f.odometer);assert.deepEqual(r,f);assert.ok(actual.height.every(v=>v<4+loss));assert.equal(actual.trace.at(-1).fired,0);}
});
test('stable fields stop without added grains, while fixed finite rounds can retain unstable sites',()=>{
 const stable=Uint32Array.from({length:63},(_,i)=>i%4),saved=stable.slice(),s=sandEvolve(stable,9,7,1,0,160);assert.deepEqual(s.height,stable);assert.equal(s.trace.length,1);assert.ok(s.odometer.every(v=>v===0));assert.notEqual(s.height,stable);assert.deepEqual(stable,saved);const active=sandEvolve(new Uint32Array(35).fill(100),7,5,1,0,1);assert.ok(active.height.some(v=>v>=4));assert.equal(active.trace.length,1);
});
test('one-pixel axes and wide hops send absent edges to the sink rather than wrapping across rows',()=>{
 const a=Uint32Array.from([0,4,0,0,0,0]),s=sandRound(a,3,2,1,0);assert.deepEqual(Array.from(s.height),[1,0,1,0,1,0]);assert.equal(s.lost,1);const wide=sandRound(Uint32Array.from([16]),1,1,12,0);assert.equal(wide.height[0],0);assert.equal(wide.lost,16);
});
test('source initialization retains every native RGB pixel, integer values, seeded perturbations and independent colour channels',()=>{
 const w=1537,h=5,a=image(w,h),saved=a.slice();for(let c=0;c<3;c++){const p={...base,jitter:0,power:160},v=sandInitial(a,w,h,p,c);assert.equal(v.length,w*h);for(let i=0;i<v.length;i++)assert.equal(v[i],Math.floor(p.load*(a[i*4+c]/255)**1.6));assert.notDeepEqual(sandInitial(a,w,h,{...base,jitter:100},c),sandInitial(a,w,h,{...base,jitter:100,seed:123},c));}assert.deepEqual(a,saved);const b=a.slice();b[1201*4]^=255;const before=sandInitial(a,w,h,{...base,jitter:0},0),after=sandInitial(b,w,h,{...base,jitter:0},0);for(let i=0;i<before.length;i++)if(i!==1201)assert.equal(before[i],after[i]);assert.notEqual(before[1201],after[1201]);
});
test('native one-pixel injections propagate by exactly the chosen graph hop',()=>{
 const w=1537,h=3,a=new Uint32Array(w*h);a[w+1200]=12;const s=sandRound(a,w,h,1,0);assert.equal(s.height[w+1201],3);assert.equal(s.height[w+1199],3);assert.equal(s.height[1200],3);assert.equal(s.height[2*w+1200],3);assert.equal(sum(s.height),12);const hop=sandRound(a,w,h,3,0);assert.equal(hop.height[w+1203],3);assert.equal(hop.height[w+1201],0);assert.equal(hop.lost,6);
});
test('zero amount owns an unchanged original, full photo preserves RGB, and an empty black field remains black',()=>{
 const a=image(71,53),saved=a.slice(),zero=sandAvalanches(a,71,53,{...base,amount:0});assert.notEqual(zero,a);assert.deepEqual(zero,a);assert.deepEqual(sandAvalanches(a,71,53,{...base,photo:100}),a);const black=Uint8ClampedArray.from({length:71*53*4},(_,i)=>i%4===3?255:0);for(const mode of[0,1,2])assert.deepEqual(sandAvalanches(black,71,53,{...base,mode}),black);assert.deepEqual(a,saved);
});
test('all eleven controls and seed change a relevant view and reproduce when restored',()=>{
 const w=311,h=229,a=image(w,h),saved=a.slice(),initial=sandAvalanches(a,w,h,base),changes={load:100,steps:0,distance:12,loss:0,power:240,jitter:100,relief:100,mode:1,photo:90,amount:40,seed:123};for(const[key,value]of Object.entries(changes))assert.notDeepEqual(sandAvalanches(a,w,h,{...base,[key]:value}),initial,key);const layers={...base,mode:2};assert.notDeepEqual(sandAvalanches(a,w,h,{...layers,bands:24}),sandAvalanches(a,w,h,layers));assert.deepEqual(sandAvalanches(a,w,h,base),initial);assert.deepEqual(a,saved);
});
test('strata normalization follows the actual state and stable repeated requests do not invent a changed image',()=>{
 const w=31,h=23,a=image(w,h),p={...base,mode:1,loss:4,steps:100},first=sandAvalanches(a,w,h,p);assert.deepEqual(sandAvalanches(a,w,h,{...p,steps:160}),first);const state={height:new Uint32Array(w*h).fill(2),odometer:new Uint32Array(w*h).fill(3)},out=new Uint8ClampedArray(a.length);sandColour(a,w,h,state,{...base,relief:0,photo:100},0,1,out);for(let i=0;i<w*h;i++)assert.equal(out[i*4],a[i*4]);
});
test('extreme parameters, tiny axes and each representation preserve opaque shape without source mutation',()=>{
 for(const[w,h]of[[1,1],[1,31],[31,1],[67,53]])for(const mode of[0,1,2]){const a=image(w,h),saved=a.slice(),out=sandAvalanches(a,w,h,{...base,load:128,steps:160,distance:12,loss:0,power:240,jitter:100,bands:24,relief:100,mode});assert.notEqual(out,a);assert.equal(out.length,a.length);for(let i=3;i<out.length;i+=4)assert.equal(out[i],255);assert.deepEqual(a,saved);}
});
test('rendering is seeded, separates photos and partially blends its floating result before final quantization',()=>{
 const w=71,h=53,a=image(w,h),other=image(h,w),original=Math.random;Math.random=()=>{throw Error('ambient randomness');};try{const full=sandAvalanches(a,w,h,base);sandAvalanches(other,h,w,{...base,mode:2,seed:123});assert.deepEqual(sandAvalanches(a,w,h,base),full);const partial=sandAvalanches(a,w,h,{...base,amount:35});for(let i=0;i<a.length;i++)if(i%4!==3)near(partial[i],a[i]+.35*(full[i]-a[i]));}finally{Math.random=original;}
});
test('engine integrates native avalanches and common transparent composition, mix, monochrome and inversion',()=>{
 const w=67,h=53,a=image(w,h),l=makeLayer('sandavalanches');assert.deepEqual(applyFilter(a,w,h,l),sandAvalanches(a,w,h,l.params));for(let i=3;i<a.length;i+=4)a[i]=i*7%256;const saved=a.slice(),full=applyFilter(a,w,h,l),zero=applyFilter(a,w,h,{...l,params:{...l.params,mix:0}}),mono=applyFilter(a,w,h,{...l,params:{...l.params,colorMode:'mono'}}),inverted=applyFilter(a,w,h,{...l,params:{...l.params,invert:true}});for(let i=0;i<a.length;i+=4){for(let c=0;c<3;c++){near(zero[i+c],a[i+c]*a[i+3]/255+255-a[i+3],.5);assert.equal(inverted[i+c],255-full[i+c]);}assert.equal(full[i+3],255);assert.equal(mono[i],mono[i+1]);assert.equal(mono[i+1],mono[i+2]);}assert.deepEqual(a,saved);
});
test('0.46 gates colour avalanches, accepts older adaptive dots and round-trips every public recipe',()=>{
 assert.equal(ENGINE_VERSION,'0.77');assert.equal(filters.length,129);assert.equal(looks.length,261);assert.equal(filters.find(f=>f.sandavalanches).controls.length,11);const l=makeLayer('sandavalanches');assert.deepEqual(decodeRecipe(encodeRecipe([l])),[l]);for(let n=2;n<=45;n++)assert.throws(()=>decodeRecipe(JSON.stringify({...JSON.parse(encodeRecipe([l])),engine:'0.'+n})));const old=makeLayer('lbgdots');assert.deepEqual(decodeRecipe(JSON.stringify({...JSON.parse(encodeRecipe([old])),engine:'0.45'})),[old]);for(const[key,value]of[['load',0],['steps',1.5],['distance',.5],['loss',13],['power',39],['mode',1.5],['seed',.5]])assert.throws(()=>decodeRecipe(encodeRecipe([{...l,params:{...l.params,[key]:value}}])));let count=0;for(const file of fs.readdirSync(new URL('../public/recipes/',import.meta.url)).filter(f=>f.endsWith('.json'))){const look=looks.find(l=>l.id===file.slice(0,-5));assert.ok(look);assert.deepEqual(decodeRecipe(fs.readFileSync(new URL('../public/recipes/'+file,import.meta.url),'utf8')),look.layers);count++;}assert.equal(count,234);
});
