import{clamp}from'./pixels.js';
export const flowPlateDefaults={width:1.2,length:3,direction:3,iterations:2,lines:65,ink:100,flatten:25,range:20,levels:10,mode:0,amount:100};
export function flowAt(a,w,h,x,y,stride=1,c=0){x=Math.max(0,Math.min(w-1,x));y=Math.max(0,Math.min(h-1,y));const ix=Math.floor(x),iy=Math.floor(y),jx=Math.min(w-1,ix+1),jy=Math.min(h-1,iy+1),fx=x-ix,fy=y-iy;return (a[(iy*w+ix)*stride+c]*(1-fx)+a[(iy*w+jx)*stride+c]*fx)*(1-fy)+(a[(jy*w+ix)*stride+c]*(1-fx)+a[(jy*w+jx)*stride+c]*fx)*fy;}
export function flowRgb(a,w,h,x,y,out=[0,0,0]){x=Math.max(0,Math.min(w-1,x));y=Math.max(0,Math.min(h-1,y));const ix=Math.floor(x),iy=Math.floor(y),jx=Math.min(w-1,ix+1),jy=Math.min(h-1,iy+1),fx=x-ix,fy=y-iy,i=(iy*w+ix)*3,j=(iy*w+jx)*3,k=(jy*w+ix)*3,l=(jy*w+jx)*3;for(let c=0;c<3;c++)out[c]=(a[i+c]*(1-fx)+a[j+c]*fx)*(1-fy)+(a[k+c]*(1-fx)+a[l+c]*fx)*fy;return out;}
export function flowGaussian(sigma){if(sigma<=0)return new Float64Array([1]);const radius=Math.ceil(3*sigma),g=new Float64Array(radius+1);let sum=0;for(let i=0;i<=radius;i++){g[i]=Math.exp(-i*i/(2*sigma*sigma));sum+=g[i]*(i?2:1);}for(let i=0;i<g.length;i++)g[i]/=sum;return g;}
export function flowBlur(a,w,h,sigma){const g=flowGaussian(sigma),tmp=new Float32Array(a.length),out=new Float32Array(a.length);for(let y=0;y<h;y++)for(let x=0;x<w;x++){let z=0;for(let k=1-g.length;k<g.length;k++)z+=a[y*w+Math.max(0,Math.min(w-1,x+k))]*g[Math.abs(k)];tmp[y*w+x]=z;}for(let y=0;y<h;y++)for(let x=0;x<w;x++){let z=0;for(let k=1-g.length;k<g.length;k++)z+=tmp[Math.max(0,Math.min(h-1,y+k))*w+x]*g[Math.abs(k)];out[y*w+x]=z;}return out;}
export function flowSobel(l,w,h){const tx=new Float32Array(l.length),ty=new Float32Array(l.length),mag=new Float32Array(l.length);let maximum=0;for(let y=0;y<h;y++)for(let x=0;x<w;x++){const i=y*w+x,a=flowAt(l,w,h,x-1,y-1),b=flowAt(l,w,h,x,y-1),c=flowAt(l,w,h,x+1,y-1),d=flowAt(l,w,h,x-1,y),f=flowAt(l,w,h,x+1,y),g=flowAt(l,w,h,x-1,y+1),j=flowAt(l,w,h,x,y+1),k=flowAt(l,w,h,x+1,y+1),gx=c+2*f+k-a-2*d-g,gy=g+2*j+k-a-2*b-c,m=Math.sqrt(gx*gx+gy*gy);if(m>1e-10){tx[i]=-gy/m;ty[i]=gx/m;}mag[i]=m;maximum=Math.max(maximum,m);}if(maximum)for(let i=0;i<mag.length;i++)mag[i]/=maximum;return{tx,ty,mag};}
export function flowEtfPass(t,w,h,radius,axis){const tx=new Float32Array(t.tx.length),ty=new Float32Array(t.ty.length),r=Math.max(0,Math.ceil(radius));for(let y=0;y<h;y++)for(let x=0;x<w;x++){const i=y*w+x;let sx=0,sy=0;for(let k=-r;k<=r;k++){const j=axis===0?y*w+Math.max(0,Math.min(w-1,x+k)):Math.max(0,Math.min(h-1,y+k))*w+x,dot=t.tx[i]*t.tx[j]+t.ty[i]*t.ty[j],weight=.5*(t.mag[j]-t.mag[i]+1)*Math.abs(dot),sign=dot<0?-1:1;sx+=t.tx[j]*weight*sign;sy+=t.ty[j]*weight*sign;}const norm=Math.sqrt(sx*sx+sy*sy);tx[i]=norm>1e-12?sx/norm:t.tx[i];ty[i]=norm>1e-12?sy/norm:t.ty[i];}return{tx,ty,mag:t.mag};}
export function flowEtf(l,w,h,radius,iterations){let t=flowSobel(flowBlur(l,w,h,Math.max(w,h)/1000*.65),w,h);for(let n=0;n<iterations;n++)for(let axis=0;axis<2;axis++)t=flowEtfPass(t,w,h,radius,axis);return{tx:t.tx,ty:t.ty};}
// Interpolate the line field after aligning each corner to the previous direction.
export function flowPoint(w,h,x,y,q=[0,0,0,0,0,0]){x=Math.max(0,Math.min(w-1,x));y=Math.max(0,Math.min(h-1,y));const ix=Math.floor(x),iy=Math.floor(y),jx=Math.min(w-1,ix+1),jy=Math.min(h-1,iy+1);q[0]=iy*w+ix;q[1]=iy*w+jx;q[2]=jy*w+ix;q[3]=jy*w+jx;q[4]=x-ix;q[5]=y-iy;return q;}
export function flowScalarPoint(a,q){const fx=q[4],fy=q[5];return(a[q[0]]*(1-fx)+a[q[1]]*fx)*(1-fy)+(a[q[2]]*(1-fx)+a[q[3]]*fx)*fy;}
export function flowVectorPoint(t,q,px,py,out=[0,0]){const fx=q[4],fy=q[5],i=q[0],j=q[1],k=q[2],l=q[3],ax=t.tx[i],ay=t.ty[i],bx=t.tx[j],by=t.ty[j],cx=t.tx[k],cy=t.ty[k],dx=t.tx[l],dy=t.ty[l],wa=(1-fx)*(1-fy),wb=fx*(1-fy),wc=(1-fx)*fy,wd=fx*fy,sa=ax*px+ay*py<0?-1:1,sb=bx*px+by*py<0?-1:1,sc=cx*px+cy*py<0?-1:1,sd=dx*px+dy*py<0?-1:1;let vx=0,vy=0;vx+=ax*wa*sa;vy+=ay*wa*sa;vx+=bx*wb*sb;vy+=by*wb*sb;vx+=cx*wc*sc;vy+=cy*wc*sc;vx+=dx*wd*sd;vy+=dy*wd*sd;const norm=Math.sqrt(vx*vx+vy*vy);out[0]=norm>1e-12?vx/norm:0;out[1]=norm>1e-12?vy/norm:0;return out;}
export function flowRgbPoint(a,q,out=[0,0,0]){const fx=q[4],fy=q[5],i=q[0]*3,j=q[1]*3,k=q[2]*3,l=q[3]*3;for(let c=0;c<3;c++)out[c]=(a[i+c]*(1-fx)+a[j+c]*fx)*(1-fy)+(a[k+c]*(1-fx)+a[l+c]*fx)*fy;return out;}
export function flowVector(t,w,h,x,y,px,py,out=[0,0]){return flowVectorPoint(t,flowPoint(w,h,x,y),px,py,out);}
export function flowNormalDog(l,t,w,h,sigma,rho){const g1=flowGaussian(sigma),g2=flowGaussian(sigma*1.6),out=new Float32Array(l.length);for(let y=0;y<h;y++)for(let x=0;x<w;x++){const i=y*w+x,nx=-t.ty[i],ny=t.tx[i];let a=0,b=0;for(let k=1-g2.length;k<g2.length;k++){const v=flowAt(l,w,h,x+k*nx,y+k*ny);b+=v*g2[Math.abs(k)];if(Math.abs(k)<g1.length)a+=v*g1[Math.abs(k)];}out[i]=a-rho*b;}return out;}
export function flowAlong(values,t,w,h,sigma){if(sigma<=0)return values.slice();const g=flowGaussian(sigma),out=new Float32Array(values.length),v=[0,0],q=[0,0,0,0,0,0];for(let y=0;y<h;y++)for(let x=0;x<w;x++){const i=y*w+x;let sum=values[i]*g[0],weight=g[0];for(let sign=-1;sign<=1;sign+=2){let xx=x,yy=y,px=t.tx[i]*sign,py=t.ty[i]*sign;flowPoint(w,h,xx,yy,q);for(let k=1;k<g.length;k++){flowVectorPoint(t,q,px,py,v);if(!v[0]&&!v[1])break;const nx=xx+v[0],ny=yy+v[1];if(nx<0||ny<0||nx>w-1||ny>h-1)break;xx=nx;yy=ny;px=v[0];py=v[1];flowPoint(w,h,xx,yy,q);sum+=flowScalarPoint(values,q)*g[k];weight+=g[k];}}out[i]=sum/weight;}return out;}
export function flowBilateral(rgb,t,w,h,sigma,range,along,out=new Float32Array(rgb.length)){if(sigma<=0){out.set(rgb);return out;}const g=flowGaussian(sigma),v=[0,0],q=[0,0,0,0,0,0],picked=[0,0,0],den=2*range*range;for(let y=0;y<h;y++)for(let x=0;x<w;x++){const i=y*w+x,j=i*3,r=rgb[j],green=rgb[j+1],b=rgb[j+2];let sr=r*g[0],sg=green*g[0],sb=b*g[0],weight=g[0];for(let sign=-1;sign<=1;sign+=2){let xx=x,yy=y,px=t.tx[i]*sign,py=t.ty[i]*sign;flowPoint(w,h,xx,yy,q);for(let k=1;k<g.length;k++){if(along){flowVectorPoint(t,q,px,py,v);if(!v[0]&&!v[1])break;const nx=xx+v[0],ny=yy+v[1];if(nx<0||ny<0||nx>w-1||ny>h-1)break;xx=nx;yy=ny;px=v[0];py=v[1];}else{xx=x-t.ty[i]*k*sign;yy=y+t.tx[i]*k*sign;if(xx<0||yy<0||xx>w-1||yy>h-1)break;}flowPoint(w,h,xx,yy,q);flowRgbPoint(rgb,q,picked);const rr=picked[0],gg=picked[1],bb=picked[2],distance=(rr-r)**2+(gg-green)**2+(bb-b)**2,wt=g[k]*Math.exp(-distance/den);sr+=rr*wt;sg+=gg*wt;sb+=bb*wt;weight+=wt;}}out[j]=sr/weight;out[j+1]=sg/weight;out[j+2]=sb/weight;}return out;}
export function flowTone(v,levels,flatten){const u=v*(levels-1),b=Math.floor(u),f=u-b,soft=.5*(1-flatten/100),q=soft>1e-12?clamp((f-.5+soft)/(2*soft),0,1):(f>=.5?1:0);return(b+q*q*(3-2*q))/(levels-1);}
export function flowPlates(a,w,h,p=flowPlateDefaults){
 if(!p.amount)return a.slice();const n=w*h,scale=Math.max(w,h)/1000,l=new Float32Array(n);for(let i=0;i<n;i++)l[i]=(.2126*a[i*4]+.7152*a[i*4+1]+.0722*a[i*4+2])/255;
 const t=flowEtf(l,w,h,p.direction*scale,p.iterations),normal=flowNormalDog(l,t,w,h,Math.max(.35,p.width*scale),.97+.0003*p.lines),mask=flowAlong(normal,t,w,h,p.length*scale);for(let i=0;i<n;i++)mask[i]=mask[i]<0?-Math.tanh(mask[i]*255):0;
 let rgb;if(p.mode===0){rgb=new Float32Array(n*3);for(let i=0;i<n;i++)for(let c=0;c<3;c++)rgb[i*3+c]=a[i*4+c]/255;if(p.flatten>0){let buffer=new Float32Array(rgb.length);for(let k=0;k<2;k++){flowBilateral(rgb,t,w,h,2*scale*p.flatten/60,p.range/255*3,true,buffer);flowBilateral(buffer,t,w,h,.8*scale*p.flatten/60,p.range/255,false,rgb);}}}
 const out=new Uint8ClampedArray(a.length),amount=p.amount/100;for(let i=0;i<n;i++){const ink=clamp(mask[i]*p.ink/100,0,1),luma=rgb?.length?(.2126*rgb[i*3]+.7152*rgb[i*3+1]+.0722*rgb[i*3+2]):0,quant=flowTone(luma,p.levels,p.flatten),delta=(quant-luma)*p.flatten/100;for(let c=0;c<3;c++){let value;if(p.mode===0)value=clamp(rgb[i*3+c]+delta,0,1)*255*(1-ink);else value=255*(1-ink)+(p.mode===2?a[i*4+c]*.55:0)*ink;out[i*4+c]=a[i*4+c]+amount*(value-a[i*4+c]);}out[i*4+3]=255;}return out;
}
