import{rasterRender}from'./raster-relief.js';
export const knottedPhotoDefaults={shape:1,width:100,depth:65,twist:0,roll:15,tilt:24,yaw:15,turn:-20,size:92,light:60,paper:97,lift:0,repeat:3};
const TAU=Math.PI*2,unit=a=>{const n=Math.hypot(...a)||1;return a.map(v=>v/n);},cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],add=(a,b,k)=>a.map((v,i)=>v+k*b[i]);
export function knotFrame(t,p){const m=p.shape===0?1:2,n=p.shape===0?0:p.shape===1?3:5,R=2,r=p.depth/100*1.2,ct=Math.cos(m*t),st=Math.sin(m*t),cn=Math.cos(n*t),sn=Math.sin(n*t),rr=R+r*cn,center=[rr*ct,rr*st,r*sn],T=unit([-r*n*sn*ct-m*rr*st,-r*n*sn*st+m*rr*ct,r*n*cn]),N=[cn*ct,cn*st,sn],B=cross(T,N),q=p.roll*Math.PI/180+p.twist*t,W=N.map((v,i)=>v*Math.cos(q)+B[i]*Math.sin(q));return{center,T,W};}
export function knotSurface(t,s,p){const f=knotFrame(t,p);return add(f.center,f.W,s*p.width/100*1.6);}
export function knotMesh(w,h,p){const copies=p.repeat*2,steps=Math.ceil(Math.min(1440,Math.max(240,Math.ceil(Math.max(w,h)*.8)))/copies)*copies,across=8,vertices=new Float32Array((steps+1)*(across+1)*6),indices=new Uint32Array(steps*across*6),ax=p.tilt*Math.PI/180,ay=p.yaw*Math.PI/180,az=p.turn*Math.PI/180,cx=Math.cos(ax),sx=Math.sin(ax),cy=Math.cos(ay),sy=Math.sin(ay),cz=Math.cos(az),sz=Math.sin(az),rot=([x,y,z])=>{const Y=y*cx-z*sx,Z=y*sx+z*cx,X=x*cy+Z*sy,ZZ=-x*sy+Z*cy;return[X*cz-Y*sz,X*sz+Y*cz,ZZ];};let minX=Infinity,maxX=-Infinity,minY=Infinity,maxY=-Infinity,k=0,j=0;
 for(let i=0;i<=steps;i++){const t=i/steps*TAU;for(let b=0;b<=across;b++){const s=b/across-.5,P=rot(knotSurface(t,s,p)),q0=knotSurface(t-1e-5,s,p),q1=knotSurface(t+1e-5,s,p),S=knotFrame(t,p).W,N=rot(unit(cross(q1.map((v,d)=>v-q0[d]),S))),diff=Math.abs(N[0]*-.3+N[1]*-.4+N[2]*Math.sqrt(.75)),shade=1-p.light/100*(1-diff)*.7;vertices.set([...P,i/steps*w-.5,b/across*h-.5,shade],j);j+=6;minX=Math.min(minX,P[0]);maxX=Math.max(maxX,P[0]);minY=Math.min(minY,P[1]);maxY=Math.max(maxY,P[1]);}}
 for(let i=0;i<steps;i++)for(let b=0;b<across;b++){const A=i*(across+1)+b,B=A+across+1;indices.set([A,B,A+1,B,B+1,A+1],k);k+=6;}
 const scale=Math.min(w/(maxX-minX),h/(maxY-minY))*p.size/100;for(let i=0;i<vertices.length;i+=6){vertices[i]=(vertices[i]-(minX+maxX)/2)*scale+w/2;vertices[i+1]=(vertices[i+1]-(minY+maxY)/2)*scale+h/2;}
 // Per-triangle UV allows a fresh copy at each texture join, never interpolating across a wrap.
 const out=new Float32Array(indices.length*6),ix=new Uint32Array(indices.length);for(let i=0;i<indices.length;i+=3){const a=indices[i],b=indices[i+1],c=indices[i+2],middle=([a,b,c].reduce((z,k)=>z+Math.floor(k/(across+1)),0)/3)/steps,segment=Math.floor(middle*copies);for(let j=0;j<3;j++){const k=indices[i+j],u=Math.floor(k/(across+1))/steps*copies-segment;out.set(vertices.subarray(k*6,k*6+6),(i+j)*6);out[(i+j)*6+3]=(k%(across+1))/across*w-.5;out[(i+j)*6+4]=((segment%2)?1-u:u)*h-.5;ix[i+j]=i+j;}}
 return{vertices:out,indices:ix,stride:6,steps,across,scale};}
export function knottedPhoto(a,w,h,q={}){const p={...knottedPhotoDefaults,...q};return rasterRender(a,w,h,knotMesh(w,h,p),p,{samples:4});}
