export function microstructureFilters(f,c){
 const add=(value,title,url,note)=>({...value,microstructure:true,research:{title,url,note}});
 return [
 add(f('phasorweave','位相の織線','PHASOR FILAMENTS','線と面','写真の輪郭に沿って線が連続し、分岐や空洞を持つ組織へ変わる。',{frequency:75,domains:24,angle:0,disorder:15,width:95,relief:35,paper:96},[c('frequency','線の密度',15,160),c('domains','流れの局所性',6,50),c('angle','線の方向',0,180,1,'°'),c('disorder','方向の揺れ',0,100),c('width','線の太さ',15,150),c('relief','線の陰影',0,100),c('paper','下地の明るさ',0,100)],true,true),'Procedural Phasor Noise / Tricard et al., SIGGRAPH 2019','https://mfx.loria.fr/software/2023/04/28/phasornoise.html','複素Gabor核の重ね合わせから位相を取り出す原理を独立実装。写真に沿う方向、明暗による線幅、特異点付近の減衰、画素幅での縁処理は独自。論文の3D微細構造・材料特性や全機能の再現ではありません。描画1100px上限。'),
 add(f('softcells','色の軟骨','SOFT ANISOTROPIC CELLS','再構成','写真を方向を持った色面へ解き直す。面は伸び、溶け合い、細い境界で触れ合う。',{cells:220,stretch:80,reach:110,hardness:55,disorder:15,fit:20,membrane:40,texture:0},[c('cells','色面の数',40,700),c('stretch','面の伸び',0,100),c('reach','面の勢力差',0,200),c('hardness','境界の硬さ',0,100),c('disorder','方向の乱れ',0,100),c('fit','色を解く回数',0,30),c('membrane','境界の陰影',0,100),c('texture','原像の混入',0,100)],true,true),'Soft Anisotropic Diagrams / Iinbor et al., SIGGRAPH 2026','https://luckyiyi.github.io/SAD/index.html','異方的な加算重み付き距離、softmaxの色混合、近傍候補の伝播を独立実装。写真から方向を取り、固定配置に対する色の最小二乗を反復。論文の全パラメータ学習・Adam・GPU版・圧縮性能の再現ではありません。候補240px、描画900px上限。'),
 add(f('steergrain','方向を持つ皮膜','STEERED MICRORELIEF','物質','輪郭へ沿う微細な起伏が、写真の色を細かく折り曲げる。方向と光を持った表面をつくる。',{frequency:22,direction:95,angle:0,relief:62,displace:8,light:225},[c('frequency','起伏の細かさ',8,160),c('direction','方向の強さ',0,100),c('angle','方向の回転',0,180,1,'°'),c('relief','起伏の光',0,100),c('displace','像のずれ',0,100),c('light','照明の向き',0,360,1,'°')],true,true),'Steerable Perlin Noise / Rice, SIGGRAPH Talks 2025','https://disneyanimation.com/publications/steerable-perlin-noise/','Algorithm 1の計量による投影と重みの方向制御を独立実装。固有値を正、和を4未満に保つ。写真由来の方向、多尺度化、法線照明と変位は独自。流体計算・3D体積描画ではありません。表面場1000px上限。'),
 add(f('gaborcloth','波を含む色片','GABOR CHROMATIC FABRIC','再構成','色片の内側に細い波を走らせ、重なりから写真を織り直す。色と線が別々の密度で現れる。',{cells:480,size:58,stretch:95,frequency:16,cross:15,scatter:35,etch:100,paper:96},[c('cells','色片の数',40,900),c('size','重なりの幅',25,140),c('stretch','色片の伸び',0,100),c('frequency','波の密度',5,100),c('cross','方向の交差',0,100),c('scatter','色片の散開',0,100),c('etch','波の陰影',0,100),c('paper','下地の明るさ',0,100)],true,true),'3D Gabor Splatting / Watanabe et al., Eurographics 2025','https://arxiv.org/abs/2504.11003','Gaussian内の4方向の調和波と2色の混合を参照し、2D写真用の独立描画器へ翻案。写真の接線、2色採取、アルファ合成、周波数の減衰は独自。3D再構成や論文の学習・視点合成は未実装。描画1100px上限。'),
 ];
}
