import {sample} from './pixels.js';
export const mirrorDefaults={shape:1,copies:1,size:105,aspect:115,bulge:100,hole:36,turn:-12,yaw:0,pitch:0,zoom:100,paper:96,background:0};
const clamp=(x,a,b)=>Math.min(b,Math.max(a,x)),wrap=x=>x-Math.floor(x);
export function mirrorNormal(x,y,p){let nx,ny,nz,z;if(p.shape===1){const rho=Math.hypot(x,y),R=(1+p.hole/100)/2,r=(1-p.hole/100)/2,q=(rho-R)/r;if(Math.abs(q)>1||!rho)return null;z=r*Math.sqrt(Math.max(0,1-q*q));nx=q*x/rho;ny=q*y/rho;nz=z/r;}else{const d=x*x+y*y;if(d>1)return null;z=Math.sqrt(Math.max(0,1-d));nx=x;ny=y;nz=z;}const aspect=Math.sqrt(p.aspect/100),height=p.bulge/100;nx*=aspect;ny/=aspect;nz/=height;const len=Math.hypot(nx,ny,nz),angle=p.turn*Math.PI/180,ca=Math.cos(angle),sa=Math.sin(angle);return{n:[(nx*ca-ny*sa)/len,(nx*sa+ny*ca)/len,nz/len],z:z*height};}
export function mirrorDirection(n){return[2*n[2]*n[0],2*n[2]*n[1],2*n[2]*n[2]-1];}
const mirrorLongitude=u=>1-Math.abs(2*wrap(.25+u)-1);
export function mirrorUV(d,p){const yaw=p.yaw*Math.PI/180,pitch=p.pitch*Math.PI/180,a=d[0]*Math.cos(yaw)+d[2]*Math.sin(yaw),b=-d[0]*Math.sin(yaw)+d[2]*Math.cos(yaw),yy=d[1]*Math.cos(pitch)-b*Math.sin(pitch),zz=d[1]*Math.sin(pitch)+b*Math.cos(pitch),scale=100/p.zoom,u=Math.atan2(a,zz)/(2*Math.PI);return[clamp(.5+(mirrorLongitude(u)-.5)*scale,0,1),clamp(.5+Math.asin(clamp(yy,-1,1))/Math.PI*scale,0,1)];}
export function mirrorSample(a,w,h,u,v,c){return sample(a,w,h,u*w-.5,v*h-.5,c);}
export function mirrorLayout(w,h,p){const cols=Math.min(p.copies,Math.max(1,Math.ceil(Math.sqrt(p.copies*w/h)))),rows=Math.ceil(p.copies/cols),cw=w/cols,ch=h/rows,r=Math.min(cw,ch)*p.size/200,aspect=Math.sqrt(p.aspect/100),a=p.turn*Math.PI/180,ca=Math.cos(a),sa=Math.sin(a),ex=r*Math.hypot(ca/aspect,sa*aspect),ey=r*Math.hypot(sa/aspect,ca*aspect),objects=[];for(let j=0;j<rows;j++){const count=Math.min(cols,p.copies-j*cols);for(let i=0;i<count;i++)objects.push({cx:w/2+(i-(count-1)/2)*cw,cy:h/2+(j-(rows-1)/2)*ch,r,ex,ey,ca,sa,aspect,id:objects.length});}return objects;}
export function photoMirrors(a,w,h,p={},options={}){const q={...mirrorDefaults,...p},objects=options.objects||mirrorLayout(w,h,q),out=new Uint8ClampedArray(a.length),tile=options.tile||96,paper=q.paper*2.55,bg=q.background/100;for(let ty=0;ty<h;ty+=tile)for(let tx=0;tx<w;tx+=tile){const xmax=Math.min(w,tx+tile),ymax=Math.min(h,ty+tile),list=objects.filter(o=>o.cx+o.ex>=tx&&o.cx-o.ex<=xmax&&o.cy+o.ey>=ty&&o.cy-o.ey<=ymax);for(let y=ty;y<ymax;y++)for(let x=tx;x<xmax;x++){const sums=[0,0,0];for(const dy of[.25,.75])for(const dx of[.25,.75]){let winner=null,deep=-Infinity,winnerID=Infinity;const px=x+dx,py=y+dy;for(const o of list){const xx=(px-o.cx)/o.r,yy=(py-o.cy)/o.r,X=(xx*o.ca+yy*o.sa)*o.aspect,Y=(-xx*o.sa+yy*o.ca)/o.aspect,n=mirrorNormal(X,Y,q);if(n&&(n.z*o.r>deep||(n.z*o.r===deep&&o.id<winnerID))){deep=n.z*o.r;winnerID=o.id;winner=mirrorUV(mirrorDirection(n.n),q);}}for(let c=0;c<3;c++)sums[c]+=winner?mirrorSample(a,w,h,winner[0],winner[1],c):paper+(sample(a,w,h,px-.5,py-.5,c)-paper)*bg;}const index=(y*w+x)*4;for(let c=0;c<3;c++)out[index+c]=sums[c]/4;out[index+3]=255;}}return out;}
