import{gaussianBlur}from'./research-math.js';
import{colourRegions}from'./colour-peel.js';import{rasterRender}from'./raster-relief.js';
export const puffedPhotoDefaults={size:185,boundary:85,pressure:85,round:50,softness:40,tilt:25,turn:-6,fit:91,light:75,paper:96,lift:0,seed:17};
export function inflateRegions(f,p){const{W,H,ids,parts}=f,n=W*H,u=new Float32Array(n),free=new Uint8Array(n),screen=.012;for(let y=1;y<H-1;y++)for(let x=1;x<W-1;x++){const i=y*W+x,id=ids[i];if(id>=0&&[i-1,i+1,i-W,i+W].every(j=>ids[j]===id))free[i]=1;}
 let residual=0,iterations=0;for(let it=0;it<600;it++){residual=0;for(let parity=0;parity<2;parity++)for(let y=1;y<H-1;y++)for(let x=1+(y+parity)%2;x<W-1;x+=2){const i=y*W+x;if(!free[i])continue;const v=(u[i-1]+u[i+1]+u[i-W]+u[i+W]+1)/(4+screen);residual=Math.max(residual,Math.abs(v-u[i]));u[i]=v;}iterations=it+1;if(residual<1e-4)break;}
 const maxima=new Float32Array(parts.length);for(let i=0;i<n;i++)if(ids[i]>=0)maxima[ids[i]]=Math.max(maxima[ids[i]],u[i]);const z=new Float32Array(n);for(let i=0;i<n;i++)if(free[i]){const id=ids[i],height=Math.sqrt(parts[id].cells.length)*p.pressure/100*.55;z[i]=Math.pow(u[i]/(maxima[id]||1),1-p.round/100*.65)*height;}return{...f,z:gaussianBlur(z,W,H,.35+p.softness/100*1.8),raw:z,u,free,iterations,residual,screen};}
export function puffedField(a,w,h,p){return inflateRegions(colourRegions(a,w,h,p),p);}
// Cubic height interpolation avoids changes of slope at guide pixel boundaries.
function heightAt(a,w,h,x,y){x=Math.max(0,Math.min(w-1,x));y=Math.max(0,Math.min(h-1,y));const X=Math.floor(x),Y=Math.floor(y),tx=x-X,ty=y-Y,cubic=(a,b,c,d,t)=>b+.5*t*(c-a+t*(2*a-5*b+4*c-d+t*(3*(b-c)+d-a))),row=dy=>{const yy=Math.max(0,Math.min(h-1,Y+dy))*w,at=dx=>a[yy+Math.max(0,Math.min(w-1,X+dx))];return cubic(at(-1),at(0),at(1),at(2),tx);};return Math.max(0,cubic(row(-1),row(0),row(1),row(2),ty));}
export function puffedMesh(w,h,f,p){const{W,H,z}=f,E=Math.max(w,h),cols=Math.max(1,Math.ceil(w/E*Math.min(640,E))),rows=Math.max(1,Math.ceil(h/E*Math.min(640,E))),vertices=new Float32Array((cols+1)*(rows+1)*6),indices=new Uint32Array(cols*rows*6),scaleZ=E/Math.max(W,H),read=(x,y)=>heightAt(z,W,H,x/w*(W-1),y/h*(H-1))*scaleZ,turn=p.turn*Math.PI/180,tilt=p.tilt*Math.PI/180,ca=Math.cos(turn),sa=Math.sin(turn),cb=Math.cos(tilt),sb=Math.sin(tilt),rot=(x,y,Z)=>{const X=(x-w/2)*ca-(y-h/2)*sa,Y=(x-w/2)*sa+(y-h/2)*ca;return[X,Y*cb-Z*sb,Y*sb+Z*cb];};let minX=Infinity,maxX=-Infinity,minY=Infinity,maxY=-Infinity,j=0,k=0;
 for(let y=0;y<=rows;y++)for(let x=0;x<=cols;x++){const u=x/cols*w,v=y/rows*h,Z=read(u,v),dx=(read(u+1,v)-read(u-1,v))/2,dy=(read(u,v+1)-read(u,v-1))/2,N=Math.hypot(dx,dy,1),nx=-dx/N,ny=-dy/N,nz=1/N,nnx=nx*ca-ny*sa,nny=(nx*sa+ny*ca)*cb-nz*sb,nnz=(nx*sa+ny*ca)*sb+nz*cb,diff=Math.max(0,nnx*-.35+nny*-.45+nnz*Math.sqrt(.675)),rest=Math.max(.2,-sb*-.45+cb*Math.sqrt(.675)),shade=1+p.light/100*(diff-rest)*.95,P=rot(u,v,Z);vertices.set([...P,u-.5,v-.5,shade],j);j+=6;minX=Math.min(minX,P[0]);maxX=Math.max(maxX,P[0]);minY=Math.min(minY,P[1]);maxY=Math.max(maxY,P[1]);}
 for(let y=0;y<rows;y++)for(let x=0;x<cols;x++){const A=y*(cols+1)+x,B=A+cols+1;indices.set([A,A+1,B,A+1,B+1,B],k);k+=6;}const scale=Math.min(w/(maxX-minX),h/(maxY-minY))*p.fit/100;for(let i=0;i<vertices.length;i+=6){vertices[i]=(vertices[i]-(minX+maxX)/2)*scale+w/2;vertices[i+1]=(vertices[i+1]-(minY+maxY)/2)*scale+h/2;}return{vertices,indices,stride:6};}
export function puffedPhoto(a,w,h,q={}){const p={...puffedPhotoDefaults,...q},f=puffedField(a,w,h,p);return rasterRender(a,w,h,puffedMesh(w,h,f,p),p,{samples:4});}
