// Research references describe foundations, not claims of reproducing complete papers.
export function researchFilters(f,c){
 const rows=[
 ['gaussian','粒子崩壊','GAUSSIAN FIELD','楕円の色粒子へ分解し、輪郭に沿って引き伸ばす。光をまとった像の破片。',{size:12,stretch:65,scatter:28,glow:30},[c('size','粒子の大きさ',4,30),c('stretch','異方性',0,100),c('scatter','解体する距離',0,100),c('glow','粒子の発光',0,100)],'GaussianImage · ECCV 2024','https://arxiv.org/abs/2403.08551','異方性2D Gaussianの累積描画を翻案。構造テンソルで形状を決め、局所平均色を正規化重みで混合。論文の全パラメータ最適化・圧縮器は含みません。'],
 ['billboards','色片群','TEXTURED SPLATS','写真の小片が、方向を持つ薄い板として浮かぶ。裂け目にも原画の質感を残します。',{size:44,stretch:45,scatter:65,twist:65},[c('size','小片の大きさ',10,70),c('stretch','板の細長さ',0,100),c('scatter','ほどく距離',0,150),c('twist','回転の乱れ',0,100)],'Gaussian Billboards · 2024','https://studios.disneyresearch.com/2025/05/13/gaussian-billboards-expressive-2d-gaussian-splatting-with-textures/','スプラット内部のテクスチャ補間を2D写真へ翻案。原研究の3D学習・カメラ復元は行いません。'],
 ['fluid','流体剥離','FLUID ADVECTION','像を流体に乗せ、渦が次の渦を運ぶ。色の面が引き延ばされ、巻き込まれます。',{time:32,force:65,vortices:7},[c('time','流れる時間',4,70),c('force','流れの強さ',0,100),c('vortices','渦の数',2,16)],'Stable Fluids · SIGGRAPH 1999','https://www.dgp.toronto.edu/public_user/stam/reality/Research/pdf/ns.pdf','半ラグランジュ移流と圧力投影を実装。固定グリッドの2D速度場で座標を移流し、原画を再サンプルする視覚用途の簡略モデル。'],
 ['lic','磁力繊維','TENSOR / LIC','輪郭の方向を細い繊維として可視化。金属の毛並みのように、線が面を覆います。',{length:24,scale:3,emboss:65},[c('length','繊維の長さ',4,60),c('scale','束の太さ',1,8),c('emboss','光沢',0,100)],'Line Integral Convolution · 1993','https://cgl.ethz.ch/teaching/scivis_common/Literature/CabralLeedom93.pdf','平滑化した構造テンソルの接線に沿ってノイズを双方向積分し、繊維の明暗へ変換。'],
 ['kuwahara','顔料面','ANISOTROPIC PAINT','輪郭に沿って色をまとめ、筆が押しつぶしたような面をつくります。',{radius:18,anisotropy:75,sharpness:75},[c('radius','筆の大きさ',4,35),c('anisotropy','方向への伸び',0,100),c('sharpness','面の分離',10,100)],'Anisotropic Kuwahara · 2009','https://www.kyprianidis.com/p/pg2009/','構造テンソルで楕円の方向を推定。8セクターの局所平均を分散に応じて重み付けする離散近似。'],
 ['xdog','輪郭版','EXTENDED DOG','なめらかな面と、鋭い彫りの線。色面の上に、細部の密度を押し出します。',{radius:2.5,detail:60,threshold:50},[c('radius','線のスケール',.5,6,.5),c('detail','細部の強調',10,100),c('threshold','黒の密度',0,100)],'XDoG · Computers & Graphics 2012','https://www.sciencedirect.com/science/article/pii/S009784931200043X','2つのGaussianスケールの差とtanhによる連続しきい値を実装。原研究の全スタイルを再現するものではありません。'],
 ['physarum','群体網','PHYSARUM','数千の粒が像を嗅ぎ、跡を辿る。線が集まり、枝分かれする発光の網。',{time:90,sensor:9,attraction:65},[c('time','成長の時間',20,180,10),c('sensor','探る距離',3,24),c('attraction','写真への吸引',0,100)],'Jones · Physarum model 2010 / 2015','https://arxiv.org/abs/1503.06579','前方3センサーの粒子、回転、移動、堆積、拡散/減衰を実装。写真を誘引場にした独立翻案。生物の精密再現ではありません。'],
 ['turing','多尺度皮膜','MULTISCALE TURING','大小の模様が競合し、像に微細な突起と大きな皺を刻みます。',{time:60,scale:5,relief:55},[c('time','育てる時間',10,100,5),c('scale','組織の大きさ',2,10),c('relief','彫りの深さ',0,100)],'McCabe · Bridges 2010','https://archive.bridgesmathart.org/2010/bridges2010-387.pdf','複数スケールの活性/抑制と最小変動スケールの選択を実装。写真を初期場に混ぜ、色と陰影へ翻案。'],
 ['spectral','位相裂開','PHASE FRACTURE','写真を周波数へ分解し、波の位相をずらす。輪郭が別の像へ干渉します。',{shift:45,band:35,angle:25},[c('shift','位相の崩れ',0,100),c('band','作用する帯域',5,90),c('angle','裂ける方向',0,180,1,'°')],'Fourier signal processing','https://people.csail.mit.edu/dgreensp/may/diffraction.html','2D FFT・共役対称の位相操作・逆FFT。位相変形の規則は本アプリ独自の造形実験です。'],
 ['diffraction','回折像','FRESNEL FIELD','写真を光の波面として伝播。色ごとの波がずれ、光の縁と干渉が現れます。',{distance:22,phase:8,exposure:105},[c('distance','伝播する距離',0,100),c('phase','位相の深さ',0,100),c('exposure','光の露出',50,220)],'Fourier optics / Fresnel propagation','https://people.csail.mit.edu/dgreensp/may/diffraction.html','複素振幅→FFT→Fresnel伝達関数→逆FFTの強度を描画。無次元の造形操作で、撮影された実際の波面/距離の復元ではありません。'],
 ['thinfilm','干渉金属','IRIDESCENT FILM','写真の起伏に、薄膜の虹と硬い光沢を重ねます。角度と膜厚で色が反転します。',{thickness:420,relief:65,light:35,metal:85},[c('thickness','膜の厚み',80,1200,10,'nm'),c('relief','起伏',0,100),c('light','照明の向き',0,360,1,'°'),c('metal','金属の比率',0,100)],'Belcour & Barla · SIGGRAPH 2017','https://belcour.github.io/blog/research/publication/2017/05/01/brdf-thin-film.html','薄膜の干渉を参照。多波長のAiry反射率をRGB応答へ積分する独立近似。論文の解析的反エイリアス・完全なBRDFは未実装。'],
 ['caustic','集光脈','CAUSTIC NETWORK','写真の明暗をレンズの起伏へ。屈折した光が集まり、細い光脈を結びます。',{focus:55,relief:60,dispersion:45},[c('focus','焦点までの距離',0,100),c('relief','レンズの起伏',0,100),c('dispersion','色の分散',0,100)],'Geometrical optics · experimental model','https://people.csail.mit.edu/dgreensp/may/diffraction.html','輝度の勾配を薄いレンズの傾きとみなし、色別の光線を前方へ散布・蓄積。これは独自の2D集光実験で、波動回折や完全な光路追跡ではありません。'],
 ];
 return rows.map(([id,name,en,description,defaults,controls,title,url,note])=>({...f(id,name,en,'研究室',description,defaults,controls,true,['gaussian','billboards','fluid','lic','physarum','turing'].includes(id)),research:{title,url,note}}));
}
