import{yarnCrimp}from'./woven-cloth.js';
import{rasterRender}from'./raster-relief.js';
export const wovenPhotoDefaults={size:95,coverage:82,relief:95,weave:0,bend:32,shift:0,tilt:28,turn:-8,fit:92,light:80,paper:96,lift:0};
export function wovenPhotoSurface(x,y,vertical,w,h,p){const E=Math.max(w,h),nx=Math.max(1,Math.round(w/(E*p.size/1000))),ny=Math.max(1,Math.round(h/(E*p.size/1000))),px=w/nx,py=h/ny,amplitude=Math.min(px,py)*p.relief/100*.24,c=yarnCrimp(x/px,y/py,vertical,p.weave,amplitude),X=x/w-.5,Y=y/h-.5,B=p.bend/100*E*.3;
 return{z:c.height+B*(X*X-Y*Y),dx:B*2*X/w+(vertical?0:c.slope/px),dy:-B*2*Y/h+(vertical?c.slope/py:0),nx,ny,px,py};}
export function wovenPhotoMesh(w,h,p){const E=Math.max(w,h),q=wovenPhotoSurface(0,0,true,w,h,p),v=[],ix=[],a=p.turn*Math.PI/180,b=p.tilt*Math.PI/180,ca=Math.cos(a),sa=Math.sin(a),cb=Math.cos(b),sb=Math.sin(b),rotate=(x,y,z)=>{const X=x*ca-y*sa,Y=x*sa+y*ca;return[X,Y*cb-z*sb,Y*sb+z*cb];};let minX=Infinity,minY=Infinity,maxX=-Infinity,maxY=-Infinity;
 for(const vertical of[true,false]){const n=vertical?q.nx:q.ny,along=vertical?h:w,period=vertical?q.px:q.py,steps=Math.max(2,Math.ceil((vertical?q.ny:q.nx)*20)),across=4,ts=Array.from({length:steps+1},(_,i)=>i/steps*along);if(!vertical&&p.shift){const cut=p.shift>0?w-p.shift/100*w:-p.shift/100*w;if(cut>0&&cut<w&&!ts.includes(cut))ts.push(cut);ts.sort((a,b)=>a-b);}for(let strip=0;strip<n;strip++){const start=v.length/6;
  for(let j=0;j<ts.length;j++)for(let k=0;k<=across;k++){const t=ts[j],s=(strip+.5+(k/across-.5)*p.coverage/100)*period,x=vertical?s:t,y=vertical?t:s,F=wovenPhotoSurface(x,y,vertical,w,h,p),N=Math.hypot(F.dx,F.dy,1),normal=rotate(-F.dx/N,-F.dy/N,1/N),dot=Math.max(0,normal[0]*-.35+normal[1]*-.45+normal[2]*Math.sqrt(.675)),base=Math.max(.2,sb*.45+cb*Math.sqrt(.675)),other=wovenPhotoSurface(x,y,!vertical,w,h,p),periodAlong=vertical?q.py:q.px,coord=(vertical?y:x)/periodAlong,edge=Math.abs(coord-Math.floor(coord)-.5)-p.coverage/200,gap=Math.max(0,other.z-F.z),occlusion=Math.min(1,gap/(periodAlong*.1+.001))*Math.exp(-Math.max(0,edge)*periodAlong/(periodAlong*.09)),shade=(1+p.light/100*(dot-base)*.9)*(1-p.light/100*.28*occlusion),P=rotate(x-w/2,y-h/2,F.z);const photoX=vertical?x:x+p.shift/100*w,mirrorX=w-Math.abs(((photoX%(2*w))+2*w)%(2*w)-w);v.push(...P,mirrorX-.5,y-.5,shade);minX=Math.min(minX,P[0]);maxX=Math.max(maxX,P[0]);minY=Math.min(minY,P[1]);maxY=Math.max(maxY,P[1]);}
  for(let j=0;j<ts.length-1;j++)for(let k=0;k<across;k++){const A=start+j*(across+1)+k,B=A+across+1;ix.push(A,A+1,B,A+1,B+1,B);}
 }}const scale=Math.min(w/Math.max(1e-6,maxX-minX),h/Math.max(1e-6,maxY-minY))*p.fit/100;for(let i=0;i<v.length;i+=6){v[i]=(v[i]-(minX+maxX)/2)*scale+w/2;v[i+1]=(v[i+1]-(minY+maxY)/2)*scale+h/2;}return{vertices:new Float32Array(v),indices:new Uint32Array(ix),stride:6};}
export function wovenPhoto(a,w,h,q={}){const p={...wovenPhotoDefaults,...q};return rasterRender(a,w,h,wovenPhotoMesh(w,h,p),p,{samples:4});}
